## Task 3 Recommender System

In [14]:
#Importing required libraries
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
from sklearn.feature_extraction.text import CountVectorizer

In [15]:
ratings = pd.read_csv('ratings.dat', names=['UserID', 'MovieID', 'Rating', 'Timestamp'], sep='::', engine='python')
movies = pd.read_csv('movies.dat', names=['MovieID', 'Title', 'Genres'], sep='::', engine='python',encoding='latin-1')
users= pd.read_csv('users.dat', names=["UserID", "Gender", "Age", "Occupation", "Zip-code"], sep='::', engine='python',encoding='latin-1')

In [16]:
users

UserID Gender  Age  Occupation Zip-code
0          1      F    1          10    48067
1          2      M   56          16    70072
2          3      M   25          15    55117
3          4      M   45           7    02460
4          5      M   25          20    55455
...      ...    ...  ...         ...      ...
6035    6036      F   25          15    32603
6036    6037      F   45           1    76006
6037    6038      F   56           1    14706
6038    6039      F   45           0    01060
6039    6040      M   25           6    11106

[6040 rows x 5 columns]

In [17]:
ratings_with_usersID = pd.merge(left=ratings,right=users,how='inner',on='UserID')
Allcombined = pd.merge(left=ratings_with_usersID,right=movies,how='inner',on='MovieID')
Allcombined.info

<bound method DataFrame.info of          UserID  MovieID  Rating  Timestamp Gender  Age  Occupation Zip-code  \
0             1     1193       5  978300760      F    1          10    48067   
1             2     1193       5  978298413      M   56          16    70072   
2            12     1193       4  978220179      M   25          12    32793   
3            15     1193       4  978199279      M   25           7    22903   
4            17     1193       5  978158471      M   50           1    95350   
...         ...      ...     ...        ...    ...  ...         ...      ...   
1000204    5949     2198       5  958846401      M   18          17    47901   
1000205    5675     2703       3  976029116      M   35          14    30030   
1000206    5780     2845       1  958153068      M   18          17    92886   
1000207    5851     3607       5  957756608      F   18          20    55410   
1000208    5938     2909       4  957273353      M   25           1    35401   

       

In [18]:
print(Allcombined['Genres'].str.split('|'))
df=Allcombined

0                           [Drama]
1                           [Drama]
2                           [Drama]
3                           [Drama]
4                           [Drama]
                     ...           
1000204               [Documentary]
1000205                     [Drama]
1000206                     [Drama]
1000207    [Comedy, Drama, Western]
1000208               [Documentary]
Name: Genres, Length: 1000209, dtype: object


In [19]:
cv = CountVectorizer()
cv_fit = cv.fit_transform(Allcombined['Genres'].str.replace('|',' '))
print(cv.get_feature_names())
#print(cv_fit.get_feature_names())

['action', 'adventure', 'animation', 'children', 'comedy', 'crime', 'documentary', 'drama', 'fantasy', 'fi', 'film', 'horror', 'musical', 'mystery', 'noir', 'romance', 'sci', 'thriller', 'war', 'western']


In [20]:
Genres= pd.DataFrame(cv_fit.toarray(),columns = cv.get_feature_names())
Genres

action  adventure  animation  children  comedy  crime  documentary  \
0             0          0          0         0       0      0            0   
1             0          0          0         0       0      0            0   
2             0          0          0         0       0      0            0   
3             0          0          0         0       0      0            0   
4             0          0          0         0       0      0            0   
...         ...        ...        ...       ...     ...    ...          ...   
1000204       0          0          0         0       0      0            1   
1000205       0          0          0         0       0      0            0   
1000206       0          0          0         0       0      0            0   
1000207       0          0          0         0       1      0            0   
1000208       0          0          0         0       0      0            1   

         drama  fantasy  fi  film  horror  musical  mystery  noir  romance  \
0            1        0   0     0       0        0        0     0        0   
1            1        0   0     0       0        0        0     0        0   
2            1        0   0     0       0        0        0     0        0   
3            1        0   0     0       0        0        0     0        0   
4            1        0   0     0       0        0        0     0        0   
...        ...      ...  ..   ...     ...      ...      ...   ...      ...   
1000204      0        0   0     0       0        0        0     0        0   
1000205      1        0   0     0       0        0        0     0        0   
1000206      1        0   0     0       0        0        0     0        0   
1000207      1        0   0     0       0        0        0     0        0   
1000208      0        0   0     0       0        0        0     0        0   

         sci  thriller  war  western  
0          0         0    0        0  
1          0         0    0        0  
2          0         0    0        0  
3          0         0    0        0  
4          0         0    0        0  
...      ...       ...  ...      ...  
1000204    0         0    0        0  
1000205    0         0    0        0  
1000206    0         0    0        0  
1000207    0         0    0        1  
1000208    0         0    0        0  

[1000209 rows x 20 columns]

In [21]:
new_df = pd.concat([Allcombined,Genres],axis=1)
new_df.head()

UserID  MovieID  Rating  Timestamp Gender  Age  Occupation Zip-code  \
0       1     1193       5  978300760      F    1          10    48067   
1       2     1193       5  978298413      M   56          16    70072   
2      12     1193       4  978220179      M   25          12    32793   
3      15     1193       4  978199279      M   25           7    22903   
4      17     1193       5  978158471      M   50           1    95350   

                                    Title Genres  ...  film  horror  musical  \
0  One Flew Over the Cuckoo's Nest (1975)  Drama  ...     0       0        0   
1  One Flew Over the Cuckoo's Nest (1975)  Drama  ...     0       0        0   
2  One Flew Over the Cuckoo's Nest (1975)  Drama  ...     0       0        0   
3  One Flew Over the Cuckoo's Nest (1975)  Drama  ...     0       0        0   
4  One Flew Over the Cuckoo's Nest (1975)  Drama  ...     0       0        0   

   mystery  noir  romance  sci  thriller  war  western  
0        0     0        0    0         0    0        0  
1        0     0        0    0         0    0        0  
2        0     0        0    0         0    0        0  
3        0     0        0    0         0    0        0  
4        0     0        0    0         0    0        0  

[5 rows x 30 columns]

In [22]:
new_df['Gender']=new_df['Gender'].replace('M',1,inplace=True)
new_df['Gender']=new_df['Gender'].replace('F',0,inplace=True)

In [23]:
ratings_as_matrix = np.ndarray(
    shape=(np.max(df.MovieID.values), np.max(df.UserID.values)),
    dtype=np.uint8)

#print(ratings_matrix)
ratings_as_matrix

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [24]:
ratings_as_matrix[df.MovieID.values-1, df.UserID.values-1] = df.Rating.values
print(ratings_as_matrix)

[[5 0 0 ... 0 0 3]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [26]:
normalised_matrix = ratings_as_matrix - np.asarray([(np.mean(ratings_as_matrix, 1))]).T
print(normalised_matrix)

[[ 3.57400662 -1.42599338 -1.42599338 ... -1.42599338 -1.42599338
   1.57400662]
 [-0.37152318 -0.37152318 -0.37152318 ... -0.37152318 -0.37152318
  -0.37152318]
 [-0.23874172 -0.23874172 -0.23874172 ... -0.23874172 -0.23874172
  -0.23874172]
 ...
 [-0.03278146 -0.03278146 -0.03278146 ... -0.03278146 -0.03278146
  -0.03278146]
 [-0.02582781 -0.02582781 -0.02582781 ... -0.02582781 -0.02582781
  -0.02582781]
 [-0.24288079 -0.24288079 -0.24288079 ... -0.24288079 -0.24288079
  -0.24288079]]


In [32]:
covariance_matrix= np.cov(normalised_matrix)
print(covariance_matrix)

[[ 4.13030618e+00  5.75769310e-01  2.58605324e-01 ...  3.68692352e-02
  -1.89683174e-03  1.01352495e-01]
 [ 5.75769310e-01  1.16348766e+00  1.58844772e-01 ...  2.35864233e-02
   1.72608728e-04  4.73547767e-02]
 [ 2.58605324e-01  1.58844772e-01  7.54054386e-01 ...  1.23744228e-02
  -3.18657205e-03  2.89395420e-02]
 ...
 [ 3.68692352e-02  2.35864233e-02  1.23744228e-02 ...  1.28748016e-01
   2.31637842e-02  7.54942213e-02]
 [-1.89683174e-03  1.72608728e-04 -3.18657205e-03 ...  2.31637842e-02
   1.07297708e-01  5.63190257e-02]
 [ 1.01352495e-01  4.73547767e-02  2.89395420e-02 ...  7.54942213e-02
   5.63190257e-02  9.15498240e-01]]


In [28]:
A = normalised_matrix.T / np.sqrt(ratings_as_matrix.shape[0] - 1)
U, S, V = np.linalg.svd(A)
print('U=\n',U)
print('S=\n',S)
print('V=\n',V)

U=
 [[ 7.13393053e-03  1.64099327e-03  2.14622406e-03 ...  4.52266370e-03
   6.00783778e-03  8.85674875e-03]
 [ 6.40383513e-04 -2.70126226e-03 -2.00478360e-04 ...  2.54577717e-03
   5.40385541e-04 -1.55791869e-02]
 [ 6.72473390e-03 -3.34737240e-03 -3.95617989e-03 ...  1.71114905e-03
   5.91124462e-03  8.44640940e-03]
 ...
 [ 1.13666709e-02  1.80896437e-03 -5.62198713e-04 ...  7.73909103e-01
  -1.48780057e-02 -2.19959777e-03]
 [ 3.49381899e-03  1.87620989e-02 -1.08962191e-02 ... -9.78238175e-03
   3.32703088e-01 -3.14995403e-03]
 [-1.32856412e-02  4.08015550e-02 -3.63311909e-03 ... -1.09584563e-03
   5.44124149e-03  8.83627250e-02]]
S=
 [2.06617808e+01 1.06804930e+01 9.14055972e+00 ... 1.71271486e-15
 1.71271486e-15 3.80173012e-16]
V=
 [[-5.72245537e-02 -2.69349804e-02 -1.44300959e-02 ... -3.50288960e-03
  -8.19971409e-04 -1.25419482e-02]
 [-2.09461200e-02 -2.97843268e-02 -1.66998921e-02 ...  1.87545849e-03
   2.26486119e-03  5.02192377e-03]
 [ 2.86333511e-02 -8.62001932e-03  1.36557569

In [44]:
def top_cosine_similarity(data, movie_id, top_n):
    index = movie_id - 1 
    movie_row = data[index, :]
    magnitude = np.sqrt(np.einsum('ij, ij -> i', data, data))
    similarity = np.dot(movie_row, data.T) / (magnitude[index] * magnitude)
    sort_indexes = np.argsort(-similarity)
    return sort_indexes[:top_n]


def similar_movies(movie_data, movie_id, top_indies):
    print('Recommendations for Movie {0}: \n'.format(
    movie_data[movie_data.MovieID == movie_id].Title.values[0]))
    for id in top_indies + 1:
        print(movie_data[movie_data.MovieID == id].Title.values[0])

k = 50
movie_id = 6 
top_n = 10 

VT = V.T[:, :k] 
movies_indies = top_cosine_similarity(VT, movie_id, top_n)
similar_movies(movies, movie_id, movies_indexes)

Recommendations for Movie Heat (1995): 

Heat (1995)
Ronin (1998)
True Romance (1993)
Out of Sight (1998)
U Turn (1997)
King of New York (1990)
In the Line of Fire (1993)
Professional, The (a.k.a. Leon: The Professional) (1994)
Wild Things (1998)
Menace II Society (1993)


In [30]:
print(VT)

[[-0.05722455 -0.02094612  0.02863335 ... -0.02620973  0.06051542
   0.01070457]
 [-0.02693498 -0.02978433 -0.00862002 ...  0.01891212  0.04177941
  -0.00106454]
 [-0.0144301  -0.01669989  0.01365576 ... -0.00767895  0.01198254
  -0.03774839]
 ...
 [-0.00350289  0.00187546  0.00191671 ...  0.00615582  0.01056114
   0.00374833]
 [-0.00081997  0.00226486  0.00347437 ...  0.00353482  0.0099851
   0.00452786]
 [-0.01254195  0.00502192  0.02208081 ...  0.00898529  0.02015898
   0.02577483]]


In [36]:
evals,evecs=np.linalg.eig(covariance_matrix)
print("EIGEN Values:",evals)
print("EIGEN Vectors:",evecs)

EIGEN Values: [279.30422154+0.j  74.63191754+0.j  54.66225966+0.j ...   0.        +0.j
   0.        +0.j   0.        +0.j]
EIGEN Vectors: [[ 0.05722455+0.j  0.02094612+0.j -0.02863335+0.j ...  0.        +0.j
   0.        +0.j  0.        +0.j]
 [ 0.02693498+0.j  0.02978433+0.j  0.00862002+0.j ...  0.        +0.j
   0.        +0.j  0.        +0.j]
 [ 0.0144301 +0.j  0.01669989+0.j -0.01365576+0.j ...  0.        +0.j
   0.        +0.j  0.        +0.j]
 ...
 [ 0.00350289+0.j -0.00187546+0.j -0.00191671+0.j ...  0.        +0.j
   0.        +0.j  0.        +0.j]
 [ 0.00081997+0.j -0.00226486+0.j -0.00347437+0.j ...  0.        +0.j
   0.        +0.j  0.        +0.j]
 [ 0.01254195+0.j -0.00502192+0.j -0.02208081+0.j ...  0.        +0.j
   0.        +0.j  0.        +0.j]]


In [45]:
k = 50
movie_id = 6
top_n = 10

top50_evalues = evecs[:, :k] 
top_indixes = top_cosine_similarity(sliced, movie_id, top_n)
print_similar_movies(movies, movie_id, top_indixes )

Recommendations for Movie Heat (1995): 

Heat (1995)
Ronin (1998)
True Romance (1993)
Out of Sight (1998)
Cop Land (1997)
Menace II Society (1993)
Desperado (1995)
Donnie Brasco (1997)
Jackie Brown (1997)
In the Line of Fire (1993)


In [41]:
print(top50_evalues)

[[ 0.05722455+0.j  0.02094612+0.j -0.02863335+0.j ...  0.01362589+0.j
  -0.00193866+0.j -0.05997806+0.j]
 [ 0.02693498+0.j  0.02978433+0.j  0.00862002+0.j ...  0.00439231+0.j
   0.01130363+0.j  0.02143723+0.j]
 [ 0.0144301 +0.j  0.01669989+0.j -0.01365576+0.j ...  0.00700238+0.j
  -0.02176034+0.j -0.01457793+0.j]
 ...
 [ 0.00350289+0.j -0.00187546+0.j -0.00191671+0.j ...  0.00069592+0.j
  -0.00668185+0.j  0.006408  +0.j]
 [ 0.00081997+0.j -0.00226486+0.j -0.00347437+0.j ... -0.00036645+0.j
  -0.00401153+0.j  0.00217063+0.j]
 [ 0.01254195+0.j -0.00502192+0.j -0.02208081+0.j ...  0.02609   +0.j
  -0.02060116+0.j  0.01451355+0.j]]
